### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [mrkindy/ETAHttpSignature#1]
`التوقيع التوقيع غير صالح • ISFX305 دافع الضرائب المُرسل للفاتوره ليس هو نفسه الموقّع الأول على الفاتورة`

**Comment by mrkindy** [comment]
ازاي ارسلت طلب التوقيع

**Comment by MrAhmedSayedAli** [comment]
من خلال السيمبل دا (https://github.com/mrkindy/EgyptianEInvoice/blob/main/examples/submitDocument.php)
مع تغيير بيانات الفاتورة طبعا لفاتورة موجودة

**Comment by mrkindy** [comment]
السيمبل ده ﻷنشاء فاتورة جديدة يعني المفروض الداتا كلها تدخل لفاتورة جديدة

**Comment by MrAhmedSayedAli** [comment]
انا بالفعل عامل فاتورة جديدة بالبيانات كاملة (بيانات من فاتورة اصلية ) بس المشكلة فى السجنتشر نفسها 🙄

**Comment by mrkindy** [comment]
الايرور بيقول ان التوقيع مش هو الخاص الشركة اللي بتقدم الفاتورة فهل انت بتستخدم التوكن بتاع الشركة ؟

**Comment by MrAhmedSayedAli** [comment]
اه لأن جربت من من البوابة ادخال يدوى قبل عادى

**Comment by MrAhmedSayedAli** [comment]
انا هجرب تانى كدة واشوف المشكلة فين بالظبط

**Comment by mrkindy** [comment]
تمام انت ممكن تتأكد من البيانات من epass وتشوف الختم مصدر لمين هل هو نفسه حساب الشركة الضريبي ولا ﻷ

**Comment by MrAhmedSayedAli** [comment]
الختم لنفس الشحص
![Untitled](https://user-images.githubusercontent.com/7157140/174989494-cbeba1e6-a2c3-4def-83e9-6ba9d7e48d83.png)

**Comment by mrkindy** [comment]
ممكن تبعتلي رقم موبايلك على الايميل admin@mrkindy.com

**Comment by MrAhmedSayedAli** [comment]
فى حاجة شاكك فيها بس لسة هجربها بكرة (ال كلاينت والسكريت ) من حساب مفوض مش الاساسى بس معرفش هل دا مأثر ولا لا (هجرب وهبلغ حضرتك)

**Comment by mrkindy** [comment]
تمام عموماً جرب لو منفعش ابعتلي رقمك وهدخل معاك نشوف المشكلة

**Comment by MrAhmedSayedAli** [comment]
تمام وصلت للمشكلة [https://github.com/bassemAgmi/EInvoicingSigner/issues/9#issuecomment-1027166570](https://github.com/bassemAgmi/EInvoicingSigner/issues/9#issuecomment-1027166570)

**Comment by MrAhmedSayedAli** [comment]
الى كان موجود توقيع اليكترونى وليس ختم 🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by mrkindy** [comment]
طيب الحمدلله ... التوقيع الالكتروني اتلغى من كام شهر وبيكون لشخص مش للشركة وحالياً بيطلب ختم الكتروني ... عموماً لو فيه اي مشكلة ابقى افتح بيها ايشو جديدة
